# Warning: only edit this file inside the images git repository.
# If you are looking at this file in your root directory on your computer, editing it does nothing.

# The image will be at ghcr.io/yourusername/name
name: ublue
# The native container image to build on top of
# Warning: Non-uBlue images might function unexpectly
base-image: ghcr.io/ublue-os/silverblue-main
# What fedora version to use. Use an explicit version or `latest`.
# If you use `latest`, you will be automatically updated
# to the next major version assuming the image you're using as your base container
# builds with the tag (all uBlue images do this).
fedora-version: 38
# This description will be visible in the container metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/
# These scripts will be executed during the container build
# Place scripts in scripts/ and put the corresponding filename here
scripts:
#  - example.sh

# a list of urls of .repo files that should be added to your system
# this is the proper way to add copr repos to your image
extrarepos:
# example:
# - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-37/atim-starship-fedora-37.repo

# These rpms will be installed from the fedora repository
# using rpm-ostree and will be preinstalled in the final image
rpms:
  # needed for yafti (the first boot installer) (remove if you're not using yafti)
  - python3-pip
  - libadwaita # libadwaita comes with silverblue, but not with other flavors
  # add your own below
  - flatpak-builder
  - fzf
  - git-crypt
  - nautilus-python
  - neovim
  - nextcloud-client
  - nextcloud-client-nautilus
  - ripgrep
  - simple-scan
  - stow
  - tmux
  - ulauncher
  - zsh
# These Flatpaks (from flathub) will be available for install on boot
# this is just an example selection.
# If you leave this empty you can use yafti for post-boot installation
flatpaks:
  - org.mozilla.firefox
  - org.mozilla.Thunderbird
  - com.mattjakeman.ExtensionManager
  - org.libreoffice.LibreOffice
  - org.gnome.DejaDup
  - org.gustavoperedo.FontDownloader
  - com.github.tchx84.Flatseal
  - io.github.celluloid_player.Celluloid
  - com.belmoussaoui.Authenticator
  - com.belmoussaoui.Decoder
  - com.github.jeromerobert.pdfarranger
  - com.github.junrrein.PDFSlicer
  - com.github.xournalpp.xournalpp
  - com.spotify.Client
  - com.valvesoftware.Steam
  - com.visualstudio.code
  - md.obsidian.Obsidian
  - org.audacityteam.Audacity
  - org.bluej.BlueJ
  - org.greenfoot.Greenfoot
  - org.cryptomator.Cryptomator
  - org.geogebra.GeoGebra
  - org.gimp.GIMP
  - org.gnome.Connections
  - org.inkscape.Inkscape
  - org.processing.processingide
  - org.signal.Signal
  - org.turbowarp.TurboWarp
